### ISSUE TITLE
大佬最新版本workerman/mqtt，mqtt下的client.php 引入Time.php 是不是少了个Lib

### ISSUE THREAD

**Issue by aaaanker** [walkor/mqtt#15]
use \Workerman\Lib\Timer;

**Comment by walkor** [comment]
\Workerman\Lib\Timer; 是很老版本 workerman的用法

**Comment by aaaanker** [comment]
我从composer 下载的 workerman/mqtt 1.2，里面的Workerman的Timer.php命名空间是 namespace Workerman\Lib;，mqtt的client.php 是 use \Workerman\Timer，报错找不到Timer.php，可能是composer的问题吧
