### ISSUE TITLE
workerman/mqtt mqtt 5，在PHP8.1下报错错 ErrorException: Calling static trait method Workerman\Mqtt\Handle\EncodeTrait::packString is deprecated, it should only be called on a class using the trait

### ISSUE THREAD

**Issue by Lucian0763** [walkor/mqtt#19]
在 trait 上调用 static 元素[ ¶](https://www.php.net/manual/zh/migration81.deprecated.php#migration81.deprecated.core.static-trait)
在 trait 上直接调用 static 方法、直接访问 static 属性的行为已被废弃。静态方法和属性只能在使用了 trait 的类上被访问。

**Comment by walkor** [comment]
`composer require workerman/mqtt ^v1.5`

**Comment by Lucian0763** [comment]
ok，已升级至1.5。
