### ISSUE TITLE
Error: Mqtt client: Connection fail

### ISSUE THREAD

**Issue by kazuser** [walkor/mqtt#2]
Hi there! We can't connect to **mqtt://test.mosquitto.org:1883**

![error](https://user-images.githubusercontent.com/3335273/43603623-44a365b8-96b5-11e8-8014-a4fef282c680.png)

Could you please fix it?

**Comment by walkor** [comment]
The service ```mqtt://test.mosquitto.org``` is not under our control.
You can install mosquitto local and test.
